SELECT D.ID, IFNULL(E.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA D LEFT JOIN (
    SELECT C.ID, COUNT(*) AS CHILD_COUNT
    FROM (
        SELECT A.ID, B.ID AS CHILD_ID
        FROM ECOLI_DATA A LEFT JOIN ECOLI_DATA B
            ON A.ID = B.PARENT_ID
        WHERE B.PARENT_ID IS NOT NULL
    ) C
    GROUP BY C.ID
) E
    ON D.ID = E.ID;
