SELECT D.ITEM_ID, D.ITEM_NAME, D.RARITY
FROM (
    SELECT B.ITEM_ID
    FROM (
            SELECT *
            FROM ITEM_INFO
            WHERE RARITY = 'RARE'
    ) A INNER JOIN ITEM_TREE B
        ON A.ITEM_ID = B.PARENT_ITEM_ID
) C INNER JOIN ITEM_INFO D
    ON C.ITEM_ID = D.ITEM_ID
ORDER BY D.ITEM_ID DESC;